from __future__ import annotations

from app.models import CliCommandSpec


CLI_COMMANDS = [
    CliCommandSpec(
        name="install",
        command="sh scripts/install.sh",
        purpose="Install frontend and backend dependencies, initialize local directories, and create env templates.",
        repeatable=True,
        reads=["package.json", "backend/requirements.txt"],
        writes=[".env", "backend/.data/"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the install log, Python version, Node version, and failed dependency command.",
    ),
    CliCommandSpec(
        name="run",
        command="sh scripts/run.sh",
        purpose="Start the local FastAPI backend and Vite frontend.",
        repeatable=True,
        reads=[".env"],
        writes=["logs/"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect logs/backend.log, logs/frontend.log, and the port reported as unavailable.",
    ),
    CliCommandSpec(
        name="setup-llm",
        command="sh scripts/setup-llm.sh",
        purpose="Configure a Claude or OpenAI-compatible model Provider using environment-variable key references.",
        repeatable=True,
        reads=[".env"],
        writes=[".env", "config/providers.local.json"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the selected protocol, base URL, model, key environment variable name, and write path.",
    ),
    CliCommandSpec(
        name="doctor",
        command="sh scripts/doctor.sh",
        purpose="Check local dependencies, ports, database path, Provider config, and optional connection test readiness.",
        repeatable=True,
        reads=[".env", "config/providers.local.json", "backend/.data/"],
        writes=[],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the failed check name and the command output from doctor.",
    ),
    CliCommandSpec(
        name="clean-artifacts",
        command="sh scripts/clean-artifacts.sh",
        purpose="Clean generated artifacts and logs while preserving drafts, history, and Provider configuration.",
        repeatable=True,
        reads=["backend/.data/artifacts", "logs/"],
        writes=["backend/.data/artifacts", "logs/"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the clean target path and the confirmation mode used.",
    ),
    CliCommandSpec(
        name="config list",
        command="sh skillforge config list",
        purpose="List configured Providers with key references only.",
        repeatable=True,
        reads=["config/providers.local.json"],
        writes=[],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the config file path and JSON parse error if present.",
    ),
    CliCommandSpec(
        name="config set",
        command="sh skillforge config set",
        purpose="Write a Provider config to config/providers.local.json and record the env variable name used for credentials.",
        repeatable=True,
        reads=[".env"],
        writes=[".env", "config/providers.local.json"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the protocol, base URL, model, key reference, and target config path.",
    ),
    CliCommandSpec(
        name="config test",
        command="sh skillforge config test",
        purpose="Test the configured Provider connection through the backend API.",
        repeatable=True,
        reads=[".env", "config/providers.local.json"],
        writes=["config/providers.local.json"],
        requiresNetwork=True,
        dangerLevel="low",
        failureSummary="Collect the Provider id, protocol, model, and failure category.",
    ),
    CliCommandSpec(
        name="generate",
        command="sh skillforge generate",
        purpose="Generate a Skill package from a local brief JSON file through the backend API.",
        repeatable=True,
        reads=["brief.json", ".env", "config/providers.local.json"],
        writes=["backend/.data/artifacts"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the draft payload path, generation id, stage, and validation report.",
    ),
    CliCommandSpec(
        name="validate",
        command="sh skillforge validate",
        purpose="Validate a rendered Skill folder structure.",
        repeatable=True,
        reads=["SKILL.md"],
        writes=[],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the Skill path and failed validation rule id.",
    ),
    CliCommandSpec(
        name="package",
        command="sh skillforge package",
        purpose="Package a rendered Skill folder as a zip with manifest and validation report.",
        repeatable=True,
        reads=["SKILL.md"],
        writes=["*.zip"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the Skill path, output zip path, and packager error.",
    ),
]
