from __future__ import annotations

from app.models import CliCommandSpec


CLI_COMMANDS = [
    CliCommandSpec(
        name="install",
        command="sh scripts/install.sh",
        purpose="Install frontend and backend dependencies and initialize local directories.",
        repeatable=True,
        reads=["package.json", "backend/requirements.txt"],
        writes=["backend/.data/"],
        requiresNetwork=True,
        dangerLevel="low",
        failureSummary="Collect the install log, Python version, Node version, and failed dependency command.",
    ),
    CliCommandSpec(
        name="run",
        command="sh scripts/run.sh",
        purpose="Start the local FastAPI backend and Vite frontend.",
        repeatable=True,
        reads=["backend/.data/", "config/providers.local.json"],
        writes=["logs/"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect logs/backend.log, logs/frontend.log, and the port reported as unavailable.",
    ),
    CliCommandSpec(
        name="setup-llm",
        command="sh scripts/setup-llm.sh",
        purpose="Configure a local Claude or OpenAI-compatible Provider. Add its key from the settings screen.",
        repeatable=True,
        reads=[],
        writes=["config/providers.local.json"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the selected protocol, base URL, model, key environment variable name, and write path.",
    ),
    CliCommandSpec(
        name="doctor",
        command="sh scripts/doctor.sh",
        purpose="Check local dependencies, ports, database path, Provider config, and optional connection test readiness.",
        repeatable=True,
        reads=["config/providers.local.json", "backend/.data/"],
        writes=[],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the failed check name and the command output from doctor.",
    ),
    CliCommandSpec(
        name="clean-artifacts",
        command="sh scripts/clean-artifacts.sh",
        purpose="Clean generated artifacts and logs while preserving drafts, history, and Provider configuration.",
        repeatable=True,
        reads=["backend/.data/artifacts", "logs/"],
        writes=["backend/.data/artifacts", "logs/"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the clean target path and the confirmation mode used.",
    ),
    CliCommandSpec(
        name="config list",
        command="sh skillforge config list",
        purpose="List configured Providers with key references only.",
        repeatable=True,
        reads=["config/providers.local.json"],
        writes=[],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the config file path and JSON parse error if present.",
    ),
    CliCommandSpec(
        name="config set",
        command="sh skillforge config set",
        purpose="Write a Provider config to config/providers.local.json without storing a plaintext credential.",
        repeatable=True,
        reads=[],
        writes=["config/providers.local.json"],
        requiresNetwork=False,
        dangerLevel="low",
        failureSummary="Collect the protocol, base URL, model, key reference, and target config path.",
    ),
]
